name: CI for Frontend & Backend

on:
  push:
    branches: [main, develop]
    paths:
      - "frontend/**"
      - "backend/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "frontend/**"
      - "backend/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [frontend, backend]

    defaults:
      run:
        working-directory: ./${{ matrix.component }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: ${{ matrix.component }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build
